export default [
  {
    id: '1',
    category: 'Clothing',
    fullName: 'Alice Alley',
    sexe: 'female',
    name: 'Bonnet',
    image: require('../../../assets/images/avatars/1.png'),
  },
  {
    id: '2',
    category: 'Books',
    fullName: 'Bob Bruce',
    sexe: 'male',
    name: 'School books',
    image: require('../../../assets/images/avatars/2.png'),
  },
  {
    id: '3',
    category: 'Documents',
    fullName: 'Carl Clay',
    sexe: 'male',
    name: 'Report 2020',
    image: require('../../../assets/images/avatars/3.png'),
  },
  {
    id: '4',
    category: 'IT',
    fullName: 'Ford Fiesta',
    sexe: 'male',
    name: 'Laptop Dell',
    image: require('../../../assets/images/avatars/5.png'),
  },
  {
    id: '5',
    category: 'Maintainance',
    fullName: 'Emily Estella',
    sexe: 'female',
    name: 'Screwdrivers',
    image: require('../../../assets/images/avatars/6.png'),
  },
  {
    id: '6',
    category: 'Vehicules',
    fullName: 'David Darwin',
    sexe: 'male',
    name: 'Peugeot 106',
    image: require('../../../assets/images/avatars/4.png'),
  },
  {
    id: '7',
    category: 'Vehicules',
    fullName: 'George Gustavo',
    sexe: 'male',
    name: 'Peugeot 106',
    image: require('../../../assets/images/avatars/7.png'),
  },
  {
    id: '8',
    category: 'Vehicules',
    fullName: 'Henry Hard',
    sexe: 'male',
    name: 'Peugeot 106',
    image: require('../../../assets/images/avatars/8.png'),
  },
  {
    id: '9',
    category: 'Vehicules',
    fullName: 'Isabela Ingrid',
    sexe: 'female',
    name: 'Peugeot 106',
    image: require('../../../assets/images/avatars/9.png'),
  },
];
