export const items = [
  {
    title: 'saturday, march 31th',
    data: [
      {
        id: '1',
        category: 'Clothing',
        person: 'Alice Alley',
        ribbonColor: '#FFC107',
        name: 'Bonnet',
        image: require('../../../assets/images/dummy/1.jpg'),
      },
      {
        id: '2',
        category: 'Books',
        person: 'Bob Bruce',
        ribbonColor: '#009688',
        name: 'School books',
        image: require('../../../assets/images/dummy/2.jpg'),
      },
    ],
  },
  {
    title: 'thursday, march 25th',
    data: [
      {
        id: '3',
        category: 'Documents',
        person: 'Carl Clay',
        ribbonColor: '#FF4081',
        name: 'Report 2020',
        image: require('../../../assets/images/dummy/3.jpg'),
      },
      {
        id: '4',
        category: 'Vehicules',
        person: 'David Darwin',
        ribbonColor: '#673AB7',
        name: 'Peugeot 106',
        image: require('../../../assets/images/dummy/4.jpg'),
      },
      {
        id: '5',
        category: 'IT',
        person: 'Emily Estella',
        ribbonColor: '#FF5722',
        name: 'Laptop Dell',
        image: require('../../../assets/images/dummy/5.jpg'),
      },
      {
        id: '6',
        category: 'Maintainance',
        person: 'Ford Fiesta',
        ribbonColor: '#8BC34A',
        name: 'Screwdrivers',
        image: require('../../../assets/images/dummy/6.jpg'),
      },
      {
        id: '7',
        category: 'Materials',
        person: 'Guillaume Gérard',
        ribbonColor: '#FFC107',
        name: 'Camera Nikon 4K',
        image: require('../../../assets/images/dummy/7.jpg'),
      },
    ],
  },
  {
    title: 'monday, march 22nd',
    data: [
      {
        id: '8',
        category: 'Tools',
        person: 'Helary Hans',
        ribbonColor: '#FFEB3B',
        name: 'Shovel',
        image: require('../../../assets/images/dummy/8.jpg'),
      },
      {
        id: '9',
        category: 'Furnitures',
        person: 'John Judy',
        ribbonColor: '#795548',
        name: 'Chair',
        image: require('../../../assets/images/dummy/9.jpg'),
      },
      {
        id: '10',
        category: 'Fixed',
        person: 'Kyle Kimber',
        ribbonColor: '#F8BBD0',
        name: 'Samsung air conditioner',
        image: require('../../../assets/images/dummy/10.jpg'),
      },
    ],
  },
];
